
package introsde.business.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import introsde.storage.ws.MeasureDefinition;
import introsde.storage.ws.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BusinessLogicLSCoach", targetNamespace = "http://ws.business.introsde/")
@XmlSeeAlso({
    introsde.business.ws.ObjectFactory.class,
    introsde.storage.ws.ObjectFactory.class
})
public interface BusinessLogicLSCoach {


    /**
     * 
     * @return
     *     returns java.util.List<introsde.storage.ws.Person>
     */
    @WebMethod
    @WebResult(name = "peopleWithLifeStatusCalculation", targetNamespace = "")
    @RequestWrapper(localName = "getPeopleWithLocalLifeStatusCalculation", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetPeopleWithLocalLifeStatusCalculation")
    @ResponseWrapper(localName = "getPeopleWithLocalLifeStatusCalculationResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetPeopleWithLocalLifeStatusCalculationResponse")
    @Action(input = "http://ws.business.introsde/BusinessLogicLSCoach/getPeopleWithLocalLifeStatusCalculationRequest", output = "http://ws.business.introsde/BusinessLogicLSCoach/getPeopleWithLocalLifeStatusCalculationResponse")
    public List<Person> getPeopleWithLocalLifeStatusCalculation();

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "boolean", targetNamespace = "")
    @RequestWrapper(localName = "syncWeightToDB", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SyncWeightToDB")
    @ResponseWrapper(localName = "syncWeightToDBResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SyncWeightToDBResponse")
    @Action(input = "http://ws.business.introsde/BusinessLogicLSCoach/syncWeightToDBRequest", output = "http://ws.business.introsde/BusinessLogicLSCoach/syncWeightToDBResponse")
    public Boolean syncWeightToDB(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns introsde.storage.ws.Person
     */
    @WebMethod
    @WebResult(name = "personSynchronized", targetNamespace = "")
    @RequestWrapper(localName = "syncPersonToDB", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SyncPersonToDB")
    @ResponseWrapper(localName = "syncPersonToDBResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SyncPersonToDBResponse")
    @Action(input = "http://ws.business.introsde/BusinessLogicLSCoach/syncPersonToDBRequest", output = "http://ws.business.introsde/BusinessLogicLSCoach/syncPersonToDBResponse")
    public Person syncPersonToDB(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param name
     * @param type
     * @return
     *     returns introsde.storage.ws.MeasureDefinition
     */
    @WebMethod
    @WebResult(name = "newMeasureDefinition", targetNamespace = "")
    @RequestWrapper(localName = "setupNewDefinitioMeasure", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SetupNewDefinitioMeasure")
    @ResponseWrapper(localName = "setupNewDefinitioMeasureResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SetupNewDefinitioMeasureResponse")
    @Action(input = "http://ws.business.introsde/BusinessLogicLSCoach/setupNewDefinitioMeasureRequest", output = "http://ws.business.introsde/BusinessLogicLSCoach/setupNewDefinitioMeasureResponse")
    public MeasureDefinition setupNewDefinitioMeasure(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "boolean", targetNamespace = "")
    @RequestWrapper(localName = "syncActivitiesToDB", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SyncActivitiesToDB")
    @ResponseWrapper(localName = "syncActivitiesToDBResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SyncActivitiesToDBResponse")
    @Action(input = "http://ws.business.introsde/BusinessLogicLSCoach/syncActivitiesToDBRequest", output = "http://ws.business.introsde/BusinessLogicLSCoach/syncActivitiesToDBResponse")
    public Boolean syncActivitiesToDB(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

}
