
package introsde.business.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BusinessLogicLSCoachService", targetNamespace = "http://ws.business.introsde/", wsdlLocation = "http://localhost:6902/ws/lifecoach/businesslogic?wsdl")
public class BusinessLogicLSCoachService
    extends Service
{

    private final static URL BUSINESSLOGICLSCOACHSERVICE_WSDL_LOCATION;
    private final static WebServiceException BUSINESSLOGICLSCOACHSERVICE_EXCEPTION;
    private final static QName BUSINESSLOGICLSCOACHSERVICE_QNAME = new QName("http://ws.business.introsde/", "BusinessLogicLSCoachService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6902/ws/lifecoach/businesslogic?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSINESSLOGICLSCOACHSERVICE_WSDL_LOCATION = url;
        BUSINESSLOGICLSCOACHSERVICE_EXCEPTION = e;
    }

    public BusinessLogicLSCoachService() {
        super(__getWsdlLocation(), BUSINESSLOGICLSCOACHSERVICE_QNAME);
    }

    public BusinessLogicLSCoachService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUSINESSLOGICLSCOACHSERVICE_QNAME, features);
    }

    public BusinessLogicLSCoachService(URL wsdlLocation) {
        super(wsdlLocation, BUSINESSLOGICLSCOACHSERVICE_QNAME);
    }

    public BusinessLogicLSCoachService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUSINESSLOGICLSCOACHSERVICE_QNAME, features);
    }

    public BusinessLogicLSCoachService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusinessLogicLSCoachService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BusinessLogicLSCoach
     */
    @WebEndpoint(name = "BusinessLogicLSCoachImplPort")
    public BusinessLogicLSCoach getBusinessLogicLSCoachImplPort() {
        return super.getPort(new QName("http://ws.business.introsde/", "BusinessLogicLSCoachImplPort"), BusinessLogicLSCoach.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessLogicLSCoach
     */
    @WebEndpoint(name = "BusinessLogicLSCoachImplPort")
    public BusinessLogicLSCoach getBusinessLogicLSCoachImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.business.introsde/", "BusinessLogicLSCoachImplPort"), BusinessLogicLSCoach.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSINESSLOGICLSCOACHSERVICE_EXCEPTION!= null) {
            throw BUSINESSLOGICLSCOACHSERVICE_EXCEPTION;
        }
        return BUSINESSLOGICLSCOACHSERVICE_WSDL_LOCATION;
    }

}
